name: Build solutions

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  cpp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Compile all solutions
        run: make check
